# Generated by Django 4.1.7 on 2023-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black')], max_length=255, null=True),
        ),
    ]
