# Generated by Django 4.1.7 on 2023-03-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_phone_color_tablet_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
