# Generated by Django 4.1.7 on 2023-03-20 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_phone_date_tablet_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accassori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('condition', models.CharField(choices=[('NUOVO', 'Nuovo'), ('USATO', 'Usato'), ('RICONDIZIONATO', 'Ricondizionato')], max_length=255)),
                ('price', models.IntegerField()),
                ('color', models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black')], max_length=255, null=True)),
                ('img', models.FileField(upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
            ],
        ),
    ]
