# Generated by Django 4.1.7 on 2026-05-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_accassori'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accassori',
            new_name='Accessori',
        ),
    ]
