# Generated by Django 4.1.7 on 2026-05-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_accassori_to_accessori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.CharField(max_length=255)),
                ('img', models.FileField(blank=True, null=True, upload_to='operatori/')),
                ('colore', models.CharField(default='#6366f1', help_text='Colore HEX es. #FF0000', max_length=7)),
            ],
        ),
    ]
