# Generated by Django 4.2 on 2026-05-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_seed_operatori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessori',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.brand'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.brand'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.brand'),
        ),
    ]
