# Generated by Django 4.2 on 2026-05-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_accessori_brand_alter_phone_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabletImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='uploads/')),
                ('tablet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.tablet')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='uploads/')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.phone')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoriImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='uploads/')),
                ('accessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.accessori')),
            ],
        ),
    ]
