# Generated by Django 4.2 on 2026-05-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_tabletimage_phoneimage_accessoriimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('condition', models.CharField(choices=[('NUOVO', 'Nuovo'), ('USATO', 'Usato'), ('RICONDIZIONATO', 'Ricondizionato')], max_length=255)),
                ('price', models.IntegerField()),
                ('color', models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black')], max_length=255, null=True)),
                ('img', models.FileField(upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'PC',
                'verbose_name_plural': 'PC',
            },
        ),
        migrations.AlterModelOptions(
            name='accessori',
            options={'verbose_name': 'Accessorio', 'verbose_name_plural': 'Accessori'},
        ),
        migrations.AlterModelOptions(
            name='accessoriimage',
            options={'verbose_name': 'Immagine accessorio', 'verbose_name_plural': 'Immagini accessori'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='operatore',
            options={'verbose_name': 'Operatore', 'verbose_name_plural': 'Operatori'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Telefono', 'verbose_name_plural': 'Telefoni'},
        ),
        migrations.AlterModelOptions(
            name='phoneimage',
            options={'verbose_name': 'Immagine telefono', 'verbose_name_plural': 'Immagini telefono'},
        ),
        migrations.AlterModelOptions(
            name='tablet',
            options={'verbose_name': 'Tablet', 'verbose_name_plural': 'Tablet'},
        ),
        migrations.AlterModelOptions(
            name='tabletimage',
            options={'verbose_name': 'Immagine tablet', 'verbose_name_plural': 'Immagini tablet'},
        ),
        migrations.CreateModel(
            name='PcImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='uploads/')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.pc')),
            ],
            options={
                'verbose_name': 'Immagine PC',
                'verbose_name_plural': 'Immagini PC',
            },
        ),
        migrations.AddField(
            model_name='pc',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.brand'),
        ),
    ]
