# Generated by Django 4.2 on 2026-05-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_pc_alter_accessori_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatore',
            name='info',
            field=models.TextField(blank=True, default='', help_text='Testo libero mostrato nella pagina di dettaglio', verbose_name='Informazioni'),
        ),
    ]
