# Generated by Django 4.2 on 2026-05-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_operatore_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessori',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Disponibile'), ('PRENOTATO', 'Prenotato'), ('VENDUTO', 'Venduto')], default='', max_length=20, verbose_name='Stato'),
        ),
        migrations.AddField(
            model_name='pc',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Disponibile'), ('PRENOTATO', 'Prenotato'), ('VENDUTO', 'Venduto')], default='', max_length=20, verbose_name='Stato'),
        ),
        migrations.AddField(
            model_name='phone',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Disponibile'), ('PRENOTATO', 'Prenotato'), ('VENDUTO', 'Venduto')], default='', max_length=20, verbose_name='Stato'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Disponibile'), ('PRENOTATO', 'Prenotato'), ('VENDUTO', 'Venduto')], default='', max_length=20, verbose_name='Stato'),
        ),
    ]
