# Generated by Django 4.2 on 2026-05-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_accessori_status_pc_status_phone_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessori',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='operatore',
            name='descrizione',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='pc',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='description',
            field=models.TextField(max_length=4000),
        ),
    ]
