# Generated by Django 4.2 on 2026-05-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_accessori_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessori',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descrizione breve'),
        ),
        migrations.AddField(
            model_name='accessori',
            name='specifiche',
            field=models.TextField(blank=True, default='', verbose_name='Specifiche tecniche'),
        ),
        migrations.AddField(
            model_name='pc',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descrizione breve'),
        ),
        migrations.AddField(
            model_name='pc',
            name='specifiche',
            field=models.TextField(blank=True, default='', verbose_name='Specifiche tecniche'),
        ),
        migrations.AddField(
            model_name='phone',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descrizione breve'),
        ),
        migrations.AddField(
            model_name='phone',
            name='specifiche',
            field=models.TextField(blank=True, default='', verbose_name='Specifiche tecniche'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descrizione breve'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='specifiche',
            field=models.TextField(blank=True, default='', verbose_name='Specifiche tecniche'),
        ),
        migrations.AlterField(
            model_name='accessori',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Descrizione'),
        ),
    ]
