# Generated by Django 4.2 on 2026-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_accessori_short_description_accessori_specifiche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='brand/', verbose_name='Logo'),
        ),
    ]
