# Generated by Django 4.2 on 2026-05-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_brand_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='specifiche',
        ),
        migrations.AddField(
            model_name='phone',
            name='batteria',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Batteria'),
        ),
        migrations.AddField(
            model_name='phone',
            name='fotocamera_frontale',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fotocamera frontale'),
        ),
        migrations.AddField(
            model_name='phone',
            name='fotocamera_posteriore',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fotocamera posteriore'),
        ),
        migrations.AddField(
            model_name='phone',
            name='memoria',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Memoria'),
        ),
        migrations.AddField(
            model_name='phone',
            name='processore',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Processore'),
        ),
        migrations.AddField(
            model_name='phone',
            name='ram',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='phone',
            name='schermo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Dimensioni schermo'),
        ),
        migrations.AddField(
            model_name='phone',
            name='sim',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SIM'),
        ),
    ]
