# Generated by Django 4.2 on 2026-05-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_phone_specifiche_phone_batteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='info_aggiuntive',
            field=models.TextField(blank=True, default='', verbose_name='Informazioni aggiuntive'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='fotocamera_frontale',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Fotocamera frontale'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='fotocamera_posteriore',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Fotocamera posteriore'),
        ),
    ]
