# Generated by Django 4.2 on 2026-06-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_phone_info_aggiuntive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatore',
            name='offerta_mese',
            field=models.BooleanField(default=False, help_text='Mostra questo operatore come offerta in evidenza nella home', verbose_name='Offerta del mese'),
        ),
    ]
